<html>

<body>

<jsp:include page="my-header.html"/>

PLACEHOLDER PLACEHOLDER PLACEHOLDER PLACEHOLDER ... <br/><br/>
PLACEHOLDER PLACEHOLDER PLACEHOLDER PLACEHOLDER ... <br/><br/>
PLACEHOLDER PLACEHOLDER PLACEHOLDER PLACEHOLDER ... <br/><br/>
PLACEHOLDER PLACEHOLDER PLACEHOLDER PLACEHOLDER ... <br/><br/>
PLACEHOLDER PLACEHOLDER PLACEHOLDER PLACEHOLDER ... <br/><br/>
PLACEHOLDER PLACEHOLDER PLACEHOLDER PLACEHOLDER ... <br/><br/>

<jsp:include page="my-footer.jsp" />

</body>

</html>